create table project (
    project_id integer unsigned auto_increment primary key,
    project_code varchar(255),
    project_name varchar(255),
    pi varchar(255),
    institution varchar(255),
    project_type varchar(255),
    description varchar(255),
    unique(project_code)
) ENGINE=InnoDB;

create table sample (
    sample_id integer unsigned auto_increment primary key,
    project_id integer unsigned,
    sample_acc varchar(255),
    sample_type varchar(255),
    sample_volume varchar(255),
    volume_unit varchar(255),
    filter_min varchar(255),
    filter_max varchar(255),
    sample_description varchar(255),
    sample_name varchar(255),
    comments varchar(255),
    taxon_id varchar(255),
    collection_start_time varchar(255),
    collection_stop_time varchar(255),
    biomaterial_name varchar(255),
    description varchar(255),
    material_acc varchar(255),
    site_name varchar(255),
    latitude varchar(255),
    longitude varchar(255),
    altitude varchar(255),
    site_depth varchar(255),
    site_description varchar(255),
    country_name varchar(255),
    region varchar(255),
    habitat_name varchar(255),
    host_taxon_id varchar(255),
    host_description varchar(255),
    host_organism varchar(255),
    library_acc varchar(255),
    sequencing_method varchar(255),
    dna_type varchar(255),
    num_of_reads varchar(255),
    material_id varchar(255),
    other varchar(255),
    unique(project_id, sample_acc),
    foreign key (project_id) references project (project_id)
) ENGINE=InnoDB;
