create table project (
    project_id integer primary key,
    project_code text,
    project_name text,
    pi text,
    institution text,
    project_type text,
    description text,
    unique(project_code)
);

create table sample (
    sample_id integer primary key,
    project_id integer,
    sample_acc text,
    sample_type text,
    sample_volume text,
    volume_unit text,
    filter_min text,
    filter_max text,
    sample_description text,
    sample_name text,
    comments text,
    taxon_id text,
    collection_start_time text,
    collection_stop_time text,
    biomaterial_name text,
    description text,
    material_acc text,
    site_name text,
    latitude text,
    longitude text,
    altitude text,
    site_depth text,
    site_description text,
    country_name text,
    region text,
    habitat_name text,
    host_taxon_id text,
    host_description text,
    host_organism text,
    library_acc text,
    sequencing_method text,
    dna_type text,
    num_of_reads text,
    material_id text,
    other text,
    unique(project_id, sample_acc)
);
